openapi: 3.0.3
info:
  title: ML microservice
  description: |-
    This is a machine learning microservice server used to predict student's admission status.
    
    Some useful links:
    - [ Hw4 repository](https://github.com/CMU-313/fall-22-hw4-valgrind-warriors)

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11

servers:
  - url: http://127.0.0.1:5000

paths:
  /:
    get:
      summary: Receive a welcome message from our microservice
      description: Return a welcome message from our microservice
      responses:
        '200':
          description: successful operation
          content:
             text/plain:
              schema:
                type: string
                example: welcome
        '400':
          description: Invalid status value
         
      
    
  
  /predict/score:
    get:
      summary: predict G3 score of the student
      description: Given students' information of study time, class failures, workday and weekend alcohol consumption, health, absences, G1 and G2 scores, give a numeric prediction the G3 score of the student
      parameters:
        - in: query
          name: studytime
          schema:
            type: integer
          description: weekly study time ( 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
        - in: query
          name: failures
          schema:
            type: integer
          description: number of past class failures (n if 1<=n<3, else 4)
        - in: query
          name: Dalc
          schema:
            type: integer
          description: workday alcohol consumption (from 1 - very low to 5 - very high)
        - in: query
          name: Walc
          schema:
            type: integer
          description: weekend alcohol consumption (from 1 - very low to 5 - very high)
        - in: query
          name: health
          schema:
            type: integer
          description: current health status (from 1 - very bad to 5 - very good)
        - in: query
          name: absences
          schema:
            type: integer
          description: number of school absences (from 0 to 93)
        - in: query
          name: G1
          schema:
            type: integer
          description: first period grade (from 0 to 20)
        - in: query
          name: G2
          schema:
            type: integer
          description: second period grade (from 0 to 20)
        
        
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  G3_score:
                    type: integer
                    description: The predicted G3 score of the student
                    example: 16
        '400':
          description: Invalid status value
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    description: error message
                    example: Missing parameter G1
  
  /predict/decision:
    get:
      summary: predict the admission status of the student
      description: Given students' information of study time, class failures, workday and weekend alcohol consumption, health, absences, G1 and G2 scores, give a numeric prediction the G3 score of the student, give the predicted admission decision of the student
      parameters:
        - in: query
          name: studytime
          schema:
            type: integer
          description: weekly study time ( 1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
        - in: query
          name: failures
          schema:
            type: integer
          description: number of past class failures (n if 1<=n<3, else 4)
        - in: query
          name: Dalc
          schema:
            type: integer
          description: workday alcohol consumption (from 1 - very low to 5 - very high)
        - in: query
          name: Walc
          schema:
            type: integer
          description: weekend alcohol consumption (from 1 - very low to 5 - very high)
        - in: query
          name: health
          schema:
            type: integer
          description: current health status (from 1 - very bad to 5 - very good)
        - in: query
          name: absences
          schema:
            type: integer
          description: number of school absences (from 0 to 93)
        - in: query
          name: G1
          schema:
            type: integer
          description: first period grade (from 0 to 20)
        - in: query
          name: G2
          schema:
            type: integer
          description: second period grade (from 0 to 20)
      responses:
        '200':
          description: successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  decision:
                    type: string
                    description: The predicted admission status of the student
                    example: yes
        '400':
          description: Invalid status value
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_message:
                    type: string
                    description: error message
                    example: Missing parameter G1
  

  
  
